### ISSUE TITLE
Add support for wagtail 1.10 + / django 1.11.x

### ISSUE THREAD

**Issue by frague59** [torchbox/wagtailsurveys#3]
For now, installing wagtailsurveys with django 1.11(.1) and wagtail 1.10 fails: 

+ setup.py: Django>=1.8.1,<1.10

Thanks !

**Comment by nicktobolski** [comment]
What's the challenge with this? Why is it failing?

**Comment by m1kola** [comment]
Sorry for the very late response. The reason why we are not paying a lot of attention to this repo is that Wagtail's [Form builder now supports customisations](http://docs.wagtail.io/en/v2.4/reference/contrib/forms/customisation.html) described in the readme for this project.

I think, this issue was fixed in #5 & #7, so I'm closing this issue, but I recommend updating your projects to use Wagtail's Form builder anyway.
